#! /bin/bash
#
# This script convert some shaders from Shadertoy to the gst-glshader
# filter API. This is only working with Shadertoy shaders that are
# only using image code (mainImage()), using only one texture in
# iChannel0.
#

# Print header
echo "/*"
if [ -n "${SHADERTOY_ID}" ] ; then
    echo " * Original shader from: https://www.shadertoy.com/view/${SHADERTOY_ID}"
    echo " *"
fi
echo " * Automatically converted by st-to-gstsh script"
echo " */"
echo

cat <<END_OF_HEADER
#ifdef GL_ES
precision mediump float;
#endif

// gst-glshader uniforms
uniform float time;
uniform float width;
uniform float height;
uniform sampler2D tex;

// shadertoy globals
float iGlobalTime = 0.0;
vec3  iResolution = vec3(0.0);
vec3  iMouse = vec3(0.0);
vec4  iDate = vec4(0.0);

#define iChannel0 tex
#define texture(t,c) texture2D(t,c)

// Protect gst-glshader names
#define time        gstemu_time
#define width       gstemu_width
#define height      gstemu_height

// --------[ Original ShaderToy begins here ]---------- //
END_OF_HEADER

# Just pass through the Shadertoy code...
cat

# Then print the footer
cat <<END_OF_FOOTER
// --------[ Original ShaderToy ends here ]---------- //

#undef time
#undef width
#undef height

void main(void)
{
  iResolution = vec3(width, height, 0.0);
  iGlobalTime = time;
  iDate.w = time;

  mainImage(gl_FragColor, gl_FragCoord.xy);
}
END_OF_FOOTER
